

services:
  postgres:
    image: postgres:16
    container_name: payment-postgres
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: paymentuser
      POSTGRES_PASSWORD: paymentpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: payment-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: paymentuser
      RABBITMQ_DEFAULT_PASS: paymentpass

  transaction-service:
    build:
      context: ./transaction-service
    container_name: transaction-service
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paymentdb
      SPRING_DATASOURCE_USERNAME: paymentuser
      SPRING_DATASOURCE_PASSWORD: paymentpass

volumes:
  postgres_data: