name: CI Pipeline

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  transaction-service:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: transaction-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw test
  
  auth-service:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: auth-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5 

      - name: Set up Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw test